### ISSUE TITLE
Doesn't work with latest Postgraphile

### ISSUE THREAD

**Issue by djmccormick** [mlipscombe/postgraphile-plugin-fulltext-filter#2]
![k](https://user-images.githubusercontent.com/40710/48462055-911c3d80-e7a4-11e8-9c95-68c832ae4991.jpg)

Tried this plugin (version v1.0.0-beta.2) against Postgraphile 4.1.0-rc.1 and 4.0 without luck (same error).

**Comment by mlipscombe** [comment]
`postgraphile-plugin-fulltext-filter@1.0.0-beta.4` has been published to npm, which should resolve this.  Feel free to re-open if you're still having any problems.
