### ISSUE TITLE
Does not work with relations

### ISSUE THREAD

**Issue by auwtch** [mlipscombe/postgraphile-plugin-fulltext-filter#3]
https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/issues/72#issuecomment-455146491

**Comment by mlipscombe** [comment]
I've added a test for `connectionFilterRelations` and it seems to work fine here:

https://github.com/mlipscombe/postgraphile-plugin-fulltext-filter/blob/7b64aa87b5a35c38717f661fa039e0c0be2ab6f5/__tests__/fulltext.test.js#L267-L327

Can you confirm you are using the very latest version of `postgraphile-plugin-fulltext-filter`, and if so, provide an example schema that triggers the bug?

**Comment by auwtch** [comment]
I use the latest version of postgraphile, connection plugin and your plugin. Schema absolutely identical with your schema in test case.

It's a strange bug.

It works with this input values:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/4533828/51321683-7f8d3580-1a74-11e9-8c63-39a2776543a1.png">

But does not work when filter only by a client:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/4533828/51321851-ec083480-1a74-11e9-9927-a5916b484299.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/4533828/51321889-0510e580-1a75-11e9-9657-583d87944303.png">

**Comment by mlipscombe** [comment]
I added another test that matches the query you show:

https://github.com/mlipscombe/postgraphile-plugin-fulltext-filter/blob/master/__tests__/fulltext.test.js#L330-L389

This test passes.  Can you run the tests from `master` and provide a test case that fails so that I can reproduce this?

**Comment by auwtch** [comment]
Only after purge `node_modules` folder and `yarn.lock` (`yarn outdated` said everything is updated), it started to work as it should, thank you so much for your plugin.

**Comment by mlipscombe** [comment]
My pleasure! I'm glad you worked it out.
